import { FaExclamationTriangle } from 'react-icons/fa';
import ProductCard from '../shared/ProductCart';
import { useDispatch, useSelector } from 'react-redux';

import { Filter } from './Filter';
import { useEffect } from 'react';
import { fetchCategories } from '../../store/actions';
import { Loader } from '../shared/Loader';
import { CustomPagination } from '../shared/CustomPagination';
import { useProductFilter } from '../hooks/userProductFilter';

// Mock de produtos (indies e AAA)
const mockProducts = [
    {
        id: '1',
        name: 'Nine Sols',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1809540/header.jpg',
        description: 'Jogo de plataforma 2D com mecânicas inspiradas em Sekiro: Shadows Die Twice.',
        quantity: 1,
        price: 88.90,
        discount: 0,
        specialPrice: 88.90,
    },
    {
        id: '2',
        name: 'Hades 2',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/header.jpg',
        description: 'Sequência do aclamado Hades, trazendo novas histórias e mecânicas aprimoradas.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '3',
        name: 'The Plucky Squire',
        image: 'https://theongaku.s3.amazonaws.com/uploads/post/banner/1475/the-plucky-squire_large.jpg',
        description: 'Um jogo que mistura estilos artísticos, transitando entre 2D e 3D.',
        quantity: 1,
        price: 79.90,
        discount: 0,
        specialPrice: 79.90,
    },
    {
        id: '4',
        name: 'Holstin',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2235430/header.jpg',
        description: 'Um jogo de terror e suspense com perspectivas de câmera inovadoras.',
        quantity: 1,
        price: 69.90,
        discount: 0,
        specialPrice: 69.90,
    },
    {
        id: '5',
        name: 'Voidnaught',
        image: 'https://www.metacritic.com/a/img/catalog/provider/6/12/6-1-1005531-52.jpg',
        description: 'Inspirado em Hollow Knight, com animações fluidas e jogabilidade desafiadora.',
        quantity: 1,
        price: 59.90,
        discount: 0,
        specialPrice: 59.90,
    },
    {
        id: '6',
        name: 'Anomaly Agent',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2378620/header.jpg',
        description: 'Um jogo de ação psicológica, ideal para fãs de Katana Zero.',
        quantity: 1,
        price: 49.90,
        discount: 0,
        specialPrice: 49.90,
    },
    {
        id: '7',
        name: 'Bō: Path of the Teal Lotus',
        image: 'https://gaming-cdn.com/images/products/14163/616x353/bo-path-of-the-teal-lotus-pc-jogo-steam-cover.jpg',
        description: 'Um jogo de ação com estética inspirada e vibrante no folclore oriental.',
        quantity: 1,
        price: 39.90,
        discount: 0,
        specialPrice: 39.90,
    },
    {
        id: '8',
        name: 'Gestalt: Steam & Cinder',
        image: 'https://sm.ign.com/t/ign_br/screenshot/default/gestalt-steam-cinder-capa_z91s.1024.jpg',
        description: 'Um RPG com visual steampunk e narrativa envolvente.',
        quantity: 1,
        price: 29.90,
        discount: 0,
        specialPrice: 29.90,
    },
    {
        id: '9',
        name: 'The Witcher 3',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg',
        description: 'Um épico de mundo aberto.',
        quantity: 1,
        price: 149.90,
        discount: 0,
        specialPrice: 149.90,
    },
    {
        id: '10',
        name: 'Call of Duty: MW3',
        image: 'https://cdkeyworld.ir/wp-content/uploads/2023/09/Call-of-Duty-Modern-Warfare-III-pc-cdkeyshareir-14.jpg',
        description: 'Ação intensa e multiplayer dinâmico.',
        quantity: 1,
        price: 199.90,
        discount: 0,
        specialPrice: 199.90,
    },
    {
        id: '11',
        name: 'FIFA 24',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2195250/header.jpg',
        description: 'O maior jogo de futebol do mundo.',
        quantity: 1,
        price: 109.90,
        discount: 0,
        specialPrice: 109.90,
    },
    {
        id: '12',
        name: 'Resident Evil 4',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg',
        description: 'Sobreviva ao terror neste thriller imersivo!',
        quantity: 1,
        price: 119.90,
        discount: 0,
        specialPrice: 119.90,
    },
    {
        id: '13',
        name: 'Black Myth: Wukong',
        image: 'https://gaming-cdn.com/images/news/articles/10920/cover/1000x563/black-myth-wukong-has-sold-25-million-units-30-outside-china-cover67bc518dda8ea.jpg',
        description: 'Uma aventura épica inspirada na mitologia chinesa.',
        quantity: 1,
        price: 249.90,
        discount: 0,
        specialPrice: 249.90,
    },
    {
        id: '14',
        name: 'Elden Ring',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg',
        description: 'Um RPG de mundo aberto com narrativa profunda e combates desafiadores.',
        quantity: 1,
        price: 129.90,
        discount: 0,
        specialPrice: 129.90,
    },
    {
        id: '15',
        name: 'Diablo IV',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2344520/header.jpg',
        description: 'Um RPG sombrio com exploração de masmorras e batalhas épicas.',
        quantity: 1,
        price: 139.90,
        discount: 0,
        specialPrice: 139.90,
    },
    {
        id: '16',
        name: 'Hogwarts Legacy',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg',
        description: 'Explore o mundo mágico de Harry Potter em um RPG de ação ambientado no século XIX.',
        quantity: 1,
        price: 119.90,
        discount: 0,
        specialPrice: 119.90,
    },
    {
        id: '17',
        name: 'Cyberpunk 2077',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg',
        description: 'Explore Night City em um RPG futurista de mundo aberto com visual cyberpunk.',
        quantity: 6,
        price: 199.99,
        discount: 55,
        specialPrice: 89.99,
    },
    {
        id: '18',
        name: 'Starfield',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg',
        description: 'Uma aventura espacial épica da Bethesda, explorando o vasto universo.',
        quantity: 1,
        price: 179.90,
        discount: 0,
        specialPrice: 179.90,
    },
    {
        id: '19',
        name: 'Street Fighter 6',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1364780/header.jpg',
        description: 'A evolução da clássica série de luta com novos personagens e modos.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '20',
        name: 'Helldivers II',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/553850/header.jpg',
        description: 'Um shooter cooperativo tático para salvar a galáxia contra hordas alienígenas.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '21',
        name: 'Space Marine II',
        image: 'https://d1w82usnq70pt2.cloudfront.net/wp-content/uploads/2024/09/spacemarine2featured-1536x864.jpeg',
        description: 'Batalhas brutais no universo de Warhammer 40K como um Space Marine.',
        quantity: 1,
        price: 109.90,
        discount: 0,
        specialPrice: 109.90,
    },
    {
        id: '22',
        name: 'Dragons Dogma II', 
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2054970/header.jpg',
        description: 'Um RPG com um mundo expansivo e combate estratégico contra criaturas colossais.',
        quantity: 1,
        price: 139.90,
        discount: 0,
        specialPrice: 139.90,
    },
    {
        id: '23',
        name: 'Stalker 2',
        image: 'https://gaming-cdn.com/images/products/5376/616x353/s-t-a-l-k-e-r-2-heart-of-chornobyl-pc-jogo-steam-europe-cover.jpg',
        description: 'Um survival horror em um mundo radioativo cheio de segredos e desafios.',
        quantity: 1,
        price: 79.90,
        discount: 0,
        specialPrice: 79.90,
    },
    {
        id: '24',
        name: 'Forza Horizon 5',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg',
        description: 'Um festival de corrida no México com paisagens deslumbrantes e carros incríveis.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '25',
        name: 'Dragon Age: The Veilguard',
        image: 'https://www.ndgames.com.br/wp-content/uploads/2024/06/Fundo-destaque-DAVeilguard.jpg',
        description: 'Explore uma nova história de fantasia cheia de intrigas e combates.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '26',
        name: 'Monster Hunter Wilds',
        image: 'https://gaming-cdn.com/images/products/17599/616x353/monster-hunter-wilds-deluxe-edition-deluxe-edition-pc-jogo-steam-north-america-cover.jpg',
        description: 'Cace monstros em biomas vastos e emocionantes, com ferramentas inovadoras.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '27',
        name: 'Silent Hill 2',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2124490/header.jpg',
        description: 'Uma releitura do clássico survival horror com atmosfera e narrativa intensas.',
        quantity: 1,
        price: 79.90,
        discount: 0,
        specialPrice: 79.90,
    },
    {
        id: '28',
        name: 'Horizon Forbidden West',
        image: 'https://img.odcdn.com.br/wp-content/uploads/2022/01/HORIZON-FORBIDDEN-WEST.jpg',
        description: 'Uma aventura de mundo aberto em um futuro pós-apocalíptico.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '29',
        name: 'Baldur’s Gate 3',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg',
        description: 'Um RPG de fantasia épico baseado em Dungeons & Dragons.',
        quantity: 7,
        price: 299.99,
        discount: 40,
        specialPrice: 179.99,
    },
    {
        id: '30',
        name: 'Jedi Survivor',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1774580/header.jpg',
        description: 'Continue a saga de Cal Kestis em uma aventura épica no universo Star Wars.',
        quantity: 1,
        price: 129.90,
        discount: 0,
        specialPrice: 129.90,
    },
    {
        id: '31',
        name: 'Persona 5 Royal',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/header.jpg',
        description: 'Viva a vida de estudante e lute contra a corrupção em Tóquio neste JRPG aclamado.',
        quantity: 6,
        price: 249.99,
        discount: 60,
        specialPrice: 99.99,
    },
    {
        id: '32',
        name: 'Atomic Heart',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/668580/header.jpg',
        description: 'Um shooter surreal ambientado em uma utopia soviética alternativa.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '33',
        name: 'Spider-Man: Miles Morales',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1817190/header.jpg',
        description: 'Controle Miles em uma emocionante jornada como o novo Homem-Aranha.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '34',
        name: 'The Last of Us Part I',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1888930/header.jpg',
        description: 'Aclamada história de sobrevivência em um mundo pós-apocalíptico.',
        quantity: 1,
        price: 79.90,
        discount: 0,
        specialPrice: 79.90,
    },
    {
        id: '35',
        name: 'Lies of P',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1627720/header.jpg',
        description: 'Uma reimaginação sombria de Pinóquio com combates inspirados em soulslike.',
        quantity: 1,
        price: 79.90,
        discount: 0,
        specialPrice: 79.90,
    },
    {
        id: '36',
        name: 'Wo Long: Fallen Dynasty',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1448440/header.jpg',
        description: 'Um RPG de ação na China antiga, cheio de mitologia e lutas intensas.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '37',
        name: 'Spyro Reignited Trilogy',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/996580/header.jpg',
        description: 'Reviva a trilogia do dragão roxo mais amado com visuais melhorados.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '38',
        name: 'Microsoft Flight Simulator 2024',
        image: 'https://img.odcdn.com.br/wp-content/uploads/2024/12/Design-sem-nome-24-1920x1080.jpg',
        description: 'A nova geração de simulação de voo com voos e gráficos realistas.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '39',
        name: 'Armored Core VI: Fires of Rubicon',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1888160/header.jpg',
        description: 'Pilote mechas em batalhas de tirar o fôlego.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '40',
        name: 'Resident Evil 4',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg',
        description: 'Um remake espetacular do survival horror que definiu o gênero.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '41',
        name: 'Dead Space',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1693980/header.jpg',
        description: 'Um remake aterrorizante do clássico de ficção científica e sobrevivência.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '42',
        name: 'Lords of the Fallen',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1501750/header.jpg',
        description: 'Um RPG sombrio em um mundo dividido entre luz e trevas.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '43',
        name: 'Hi-Fi Rush',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1817230/header.jpg',
        description: 'Um título inovador que mistura ação e ritmo em um mundo colorido.',
        quantity: 1,
        price: 79.90,
        discount: 0,
        specialPrice: 79.90,
    },
    {
        id: '44',
        name: 'Farcry 6',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2369390/header.jpg',
        description: 'Lidere uma revolução contra um regime autoritário em um paraíso tropical.',
        quantity: 1,
        price: 79.90,
        discount: 0,
        specialPrice: 79.90,
    },
    {
        id: '45',
        name: 'Forza Motorsport',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2440510/header.jpg',
        description: 'Simulador de corrida com foco em realismo e performance.',
        quantity: 1,
        price: 89.90,
        discount: 0,
        specialPrice: 89.90,
    },
    {
        id: '46',
        name: 'Indiana Jones',
        image: 'https://i0.wp.com/thatnerdshow.com/wp-content/uploads/2024/12/indiana-jones-and-the-great-circle_cover_2.jpg',
        description: 'Embarque em uma aventura cinematográfica com o icônico arqueólogo.',
        quantity: 1,
        price: 99.90,
        discount: 0,
        specialPrice: 99.90,
    },
    {
        id: '47',
        name: 'God of War Ragnarok',
        image: 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2021/09/god-war-ragnarok-2466115.jpg',
        description: 'Kratos e Atreus enfrentam os desafios do fim dos tempos nórdicos.',
        quantity: 1,
        price: 149.90,
        discount: 0,
        specialPrice: 149.90,
    },
    {
        id: '48',
        name: 'Hollow Knight',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg',
        description: 'Explore cavernas, cidades antigas e enfrente criaturas em um metroidvania indie aclamado.',
        quantity: 10,
        price: 59.99,
        discount: 30,
        specialPrice: 41.99,
    },
    {
        id: '49',
        name: 'Celeste',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/504230/header.jpg',
        description: 'Ajude Madeline a superar seus desafios internos em uma montanha cheia de plataformas precisas.',
        quantity: 7,
        price: 39.99,
        discount: 25,
        specialPrice: 29.99,
    },
    {
        id: '50',
        name: 'Stardew Valley',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg',
        description: 'Construa sua fazenda, faça amigos e explore cavernas neste indie de simulação.',
        quantity: 12,
        price: 29.99,
        discount: 10,
        specialPrice: 26.99,
    },
    {
        id: '51',
        name: 'God of War',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg',
        description: 'Kratos retorna em uma jornada épica com seu filho Atreus em terras nórdicas.',
        quantity: 3,
        price: 199.99,
        discount: 40,
        specialPrice: 119.99,
    },
    {
        id: '52',
        name: 'Hades',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg',
        description: 'Escape do submundo neste premiado roguelike indie da Supergiant Games.',
        quantity: 8,
        price: 79.99,
        discount: 35,
        specialPrice: 51.99,
    },
    {
        id: '53',
        name: 'Red Dead Redemption 2',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg',
        description: 'Viva o Velho Oeste em um dos maiores AAA de mundo aberto já feitos.',
        quantity: 4,
        price: 249.99,
        discount: 60,
        specialPrice: 99.99,
    },
    {
        id: '54',
        name: 'Undertale',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/391540/header.jpg',
        description: 'Um RPG indie único onde suas escolhas realmente importam.',
        quantity: 15,
        price: 19.99,
        discount: 0,
        specialPrice: 19.99,
    },
    {
        id: '55',
        name: 'Disco Elysium',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/632470/header.jpg',
        description: 'Um RPG inovador focado em narrativa e escolhas profundas.',
        quantity: 9,
        price: 99.99,
        discount: 40,
        specialPrice: 59.99,
    },
    {
        id: '56',
        name: 'DOOM Eternal',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg',
        description: 'Ação frenética e combate intenso no clássico shooter em primeira pessoa.',
        quantity: 7,
        price: 159.99,
        discount: 50,
        specialPrice: 79.99,
    },
    {
        id: '57',
        name: 'Cuphead',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/268910/header.jpg',
        description: 'Um run-and-gun com visual de desenho animado dos anos 30 e dificuldade elevada.',
        quantity: 11,
        price: 49.99,
        discount: 20,
        specialPrice: 39.99,
    },
    {
        id: '58',
        name: 'Ori and the Will of the Wisps',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1057090/header.jpg',
        description: 'Uma aventura visualmente deslumbrante e emocionante em um metroidvania premiado.',
        quantity: 10,
        price: 79.99,
        discount: 35,
        specialPrice: 51.99,
    },
    {
        id: '59',
        name: 'Dark Souls III',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/374320/header.jpg',
        description: 'Desafie-se em batalhas épicas e ambientes sombrios neste RPG de ação.',
        quantity: 5,
        price: 129.99,
        discount: 60,
        specialPrice: 51.99,
    },
    {
        id: '60',
        name: 'Slay the Spire',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/646570/header.jpg',
        description: 'Misture cartas e estratégia em um roguelike viciante.',
        quantity: 13,
        price: 49.99,
        discount: 30,
        specialPrice: 34.99,
    },
    {
        id: '61',
        name: 'It Takes Two',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/header.jpg',
        description: 'Uma aventura cooperativa premiada para dois jogadores.',
        quantity: 8,
        price: 119.99,
        discount: 50,
        specialPrice: 59.99,
    },
    {
        id: '62',
        name: 'The Legend of Heroes: Trails of Cold Steel IV',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1198090/header.jpg',
        description: 'O capítulo final de uma saga épica de JRPG.',
        quantity: 4,
        price: 199.99,
        discount: 50,
        specialPrice: 99.99,
    },
    {
        id: '63',
        name: 'Monster Hunter: World',
        image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg',
        description: 'Cace monstros gigantes em um mundo vibrante e expansivo.',
        quantity: 9,
        price: 159.99,
        discount: 60,
        specialPrice: 63.99,
    },
];



const Products = () => {
    const { products, categories, pagination } = useSelector((state) => state.product);
    const { isLoading, errorMessage } = useSelector((state) => state.errors);
    const dispatch = useDispatch();

    useProductFilter();

    useEffect(() => {
        dispatch(fetchCategories())
    }, [dispatch]);

    return (
        <div className="lg:px-14 sm:px-8 px-4 py-14 2xl:w-[90%] 2xl:mx-auto">
            <Filter categories={categories || []} />
            {isLoading && (
                <Loader text={"Fetching products..."} />
            )}
            {!isLoading && errorMessage && (
                <div className="flex items-center justify-center h-screen">
                    <FaExclamationTriangle className="text-slate-800 text-4xl mr-2" />
                    <span className='text-slate-800 text-lg font-medium'>{errorMessage}</span>
                </div>
            )}
            {!isLoading && !errorMessage && (
                <div className="min-h-[700px]">
                    <div className="pb-6 pt-14 grid 2xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-8">
                        {mockProducts.map((product) =>
                            <ProductCard key={product.id} product={product} />
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}

export default Products;